### ISSUE TITLE
Playbook for tower_credential_type uses string inputs

### ISSUE THREAD

**Issue by AlanCoding** [ansible/test-playbooks#87]
This playbook

https://github.com/ansible/test-playbooks/blob/d4b39fe0c010cf8dc9c4e6e60113664cd4bf1bbd/tower_modules/tower_credential_type/tasks/main.yml#L7-L8

Is probably going to stop working with newer version of Ansible because of increasing strictness for type checking.

You can see that these are declared to be dict type

https://github.com/ansible/ansible/blob/bc4ef99533514f0d35c24ddfe0fd4497ceb1ac8c/lib/ansible/modules/web_infrastructure/ansible_tower/tower_credential_type.py#L119-L120

But the module is passing these in as strings.

**Comment by AlanCoding** [comment]
Okay this seems to work out of the box:

```yaml
- hosts: all
  gather_facts: false
  connection: local
  tasks:
    - name: Add Tower credential type
      tower_credential_type:
        description: Credential type for Test
        name: test-credential-type
        kind: cloud
        inputs:
          fields:
            - type: string
              id: username
              label: Username
            - secret: True
              type: string
              id: password
              label: Password
          required:
            - username
            - password
        injectors:
          extra_vars:
            test: foo
```

So I don't think there was any need to take strings for these.
